// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShopping.Data;

#nullable disable

namespace OnlineShopping.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20260102185602_addedImageUrl")]
    partial class addedImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShopping.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "TechCorp",
                            CategoryId = 1,
                            Description = "Latest model smartphone with advanced features",
                            ISBN = "ELEC-001",
                            ImageUrl = "",
                            ListPrice = 799.99000000000001,
                            Price = 699.99000000000001,
                            Price100 = 599.99000000000001,
                            Price50 = 649.99000000000001,
                            Title = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Doe",
                            CategoryId = 2,
                            Description = "A thrilling science fiction novel set in a dystopian future",
                            ISBN = "BOOK-001",
                            ImageUrl = "",
                            ListPrice = 19.989999999999998,
                            Price = 14.99,
                            Price100 = 9.9900000000000002,
                            Price50 = 12.99,
                            Title = "Science Fiction Novel"
                        },
                        new
                        {
                            Id = 3,
                            Author = "FashionBrand",
                            CategoryId = 3,
                            Description = "Comfortable and stylish designer t-shirt",
                            ISBN = "CLOTH-001",
                            ImageUrl = "",
                            ListPrice = 39.990000000000002,
                            Price = 29.989999999999998,
                            Price100 = 19.989999999999998,
                            Price50 = 24.989999999999998,
                            Title = "Designer T-Shirt"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Models.Product", b =>
                {
                    b.HasOne("OnlineShopping.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
